# Generated by Django 5.1.2 on 2024-10-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plancapacitacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rut_empresa',
            field=models.CharField(default='00000000-0', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
