# Generated by Django 5.1.2 on 2024-10-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_empresa_is_active_empresa_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='password',
            field=models.CharField(default='00000000-0', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
